baseURL = "https://hop.apache.org/"
languageCode = "en-us"
title = "Hop"
relativeURLs = true
disablePathToLower = true
staticDir = ["static", "documentation"]
disableKinds = ["taxonomyTerm"]
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe= true

[markup]
    [markup.asciidocExt]
        preserveTOC = true

[params]
    openGraph = true
    images = ['https://hop.apache.org/img/hop-logo.png']
    socialProfiles = ["https://twitter.com/ApacheHop"]
    organizationLogo = "/img/hop-logo.svg"
    organizationDescription = "Apache Hop - Hop Orchestration Platform"
    Description = "Apache Hop - Hop Orchestration Platform"

[Author]
    name = "The Hop Team"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 1
    url = "/blog/"

[[menu.main]]
    name = "Documentation"
    identifier = "docs"
    weight = 1

[[menu.main]]
    name = "Getting started"
    parent = "docs"
    weight = 1
    identifier = "docs-getting-started"
    url = "/manual/latest/getting-started/"

[[menu.main]]
    name = "User manual"
    parent = "docs"
    weight = 2
    identifier = "docs-user-manual"
    url = "/manual/latest/"

[[menu.main]]
    name = "Technical Documentation"
    parent = "docs"
    weight = 3
    identifier = "docs-tech-manual"
    url = "/tech-manual/latest/"

[[menu.main]]
    name = "Developer Documentation"
    parent = "docs"
    weight = 4
    identifier = "docs-dev-manual"
    url = "/dev-manual/latest/"

[[menu.main]]
    name = "Architecture"
    parent = "docs"
    weight = 5
    identifier = "docs-architecture"
    url = "/docs/architecture/"

[[menu.main]]
    name = "Roadmap"
    parent = "docs"
    weight = 6
    identifier = "docs-roadmap"
    url = "/docs/roadmap/"

[[menu.main]]
    name = "Community"
    identifier = "community"
    weight = 2

[[menu.main]]
    name = "Contributing"
    parent = "community"
    weight = 1
    identifier = "community-contributing"
    url = "/community/contributing/"

[[menu.main]]
    name = "Tools"
    parent = "community"
    weight = 2
    identifier = "community-tools"
    url = "/community/tools/"

[[menu.main]]
    name = "Mailing Lists"
    parent = "community"
    weight = 3
    identifier = "community-mailing"
    url = "/community/mailing-list/"

[[menu.main]]
    name = "Events and User Groups"
    parent = "community"
    weight = 4
    identifier = "community-events"
    url = "/community/events/"

[[menu.main]]
    name = "Team"
    parent = "community"
    weight = 5
    identifier = "community-team"
    url = "/community/team/"

[[menu.main]]
    name = "Support"
    parent = "community"
    weight = 6
    identifier = "community-support"
    url = "/community/support/"

[[menu.main]]
    name = "Ethos"
    parent = "community"
    weight = 7
    identifier = "community-ethos"
    url = "/community/ethos/"

[[menu.main]]
    name = "Download"
    weight = 3
    identifier = "download"
    url = "/download/"

[[menu.main]]
    name = "Apache"
    identifier = "apache"
    weight = 4

[[menu.main]]
    name = "Events"
    parent = "apache"
    weight = 1
    identifier = "about-events"
    url = "https://www.apache.org/events/current-event"
    pre = "_blank"

[[menu.main]]
    name = "License"
    parent = "apache"
    weight = 2
    identifier = "about-license"
    url = "https://www.apache.org/licenses/"
    pre = "_blank"

[[menu.main]]
    name = "Thanks to our sponsors"
    parent = "apache"
    weight = 3
    identifier = "about-thanks"
    url = "https://www.apache.org/foundation/thanks.html"
    pre = "_blank"

[[menu.main]]
    name = "Apache Security"
    parent = "apache"
    weight = 4
    identifier = "about-security"
    url = "https://www.apache.org/security/"
    pre = "_blank"

[[menu.main]]
    name = "Become a sponsor"
    parent = "apache"
    weight = 5
    identifier = "about-sponsor"
    url = "https://www.apache.org/foundation/sponsorship.html"
    pre = "_blank"


[module]

  [[module.mounts]]
    source = "documentation/_/data"
    target = "data"
