site:
  title: Apache Hop
  url: https://hop.apache.org
  start_page: manual::index.adoc

content:
  sources:
  - url: git@github.com:apache/hop.git
    branches: 
      - master
      - release1.0.0
      - release1.1.0
      - release1.2.0
      - release2.0.0
      - release2.1.0
      - release/2.2.0
    start_path: /docs/hop-user-manual/
  - url: git@github.com:apache/hop.git
    branches: master
    start_path: /docs/hop-tech-manual/
  - url: git@github.com:apache/hop.git
    branches: master
    start_path: /docs/hop-dev-manual/
    
ui:
  bundle:
    url: ./antora-ui-hop/build/ui-bundle.zip

urls:
  redirect_facility: disabled
  latest_version_segment: latest
  latest_prerelease_version_segment: next

output:
  clean: true
  dir: ./documentation

runtime: 
  fetch: true  

